FORMAT: 1A
HOST: http://gtsc.leanapp.cn/

# 光速达开放平台API
光速达智能云开放平台API

## 概述
本文档用于说明私有云调用光速达智能云接口方法，主要分三部分进行相关内容定义和介绍。
- 第一部分概述，主要介绍本文档结构和主要内容。
- 第二部分主要介绍光速达智能云HTTP连接请求和安全策略，对HTTP请求格式、应答格式、签名算法等做了详细介绍，并列举实例进行相关说明。
- 第三部分主要介绍光速达智能云平台开放接口规范细则，从接口功能、定义和范例三方面对接口做了详细规定并给出使用范例。最后对有关专业用语做了名词解释，便于理解文档内容。

## 接口版本
| 版本    | 更新内容| 发布人 |  发布时间 |
|--------|-------|----|-------|
| V0.1 | 初稿待确认|  光速达 | 2016-05-10  |

## 开发者规范
开发者进行开发时，除了需要满足每个接口的规范限制、调用频率限制外，还需特别注意设备控制消息、用户数据等敏感信息的使用规范。

涉及用户数据时：

- 您的服务需要收集用户任何数据的，必须事先获得用户的明确同意，且仅应当收集为运营及功能实现目的而必要的用户数据， 同时应当告知用户相关数据收集的目的、范围及使用方式等，保障用户知情权。
- 您收集用户的数据后，必须采取必要的保护措施，防止用户数据被盗、泄漏等。
- 您在特收集的用户数据仅可以在该特定应用中使用，不得将其使用在该特定应用之外或为其他任何目的进行使用，也不得以任何方式将其提供给他人。
- 如果光速达认为您收集、使用用户数据的方式，可能损害用户体验，光速达有权要求您删除相关数据并不得再以该方式收集、使用用户数据。
- 一旦您停止使用本服务，或光速达基于任何原因终止您使用本服务，您必须立即删除全部因使用本服务而获得的数据（包括各种备份）， 且不得再以任何方式进行使用。

其他规范：

- 请勿为任何用户自动登录到光速达云平台提供代理身份验证凭据。
- 请勿提供跟踪功能，包括但不限于识别其他用户在个人主页上查看、点击等操作行为。
- 请勿自动将浏览器窗口定向到其他网页。
- 请勿设置或发布任何违反相关法规、公序良俗、社会公德等的玩法、内容等。
- 请勿公开表达或暗示，您与光速达之间存在合作关系，包括但不限于相互持股、商业往来或合作关系等，或声称光速达对您的认可。
- 完整的开发者规范和接口限制，请详见开发者接口文档，以及光速达微信公众平台开发者协议。

## 接口权限说明
需要在开放平台 http://open.gtscn.cn 申请后方可使用

## 接口调用频率限制说明
暂无相关限制

## 接口返回码说明

## 公共请求参数说明
| 参数名称 | 数据类型|描述|
|--------|--------|--------|
|timestamp |long | Unix时间戳，单位为秒，如：1448091239。如无特殊说明，需要时间戳相差在180秒以内。同样的，API接口使用的时间内容均为Unix时间戳。|
|sign | string|生成的签名信息，用于验证请求的合法性|
|nonstr | string | 随机字符串，用于提高签名安全性，最长不超过128个字节，区分大小写。
|appId |string | 在光速达智能云开放平台申请的应用的编码|

## HTTP连接请求
用户通过HTTP请求方式，从私有云调用光速达智能云开放接口，实现获取设备列表、查询报警信息、获取视频广场栏目和展示视频列表等功能。

### HTTP请求数据格式规范

```
{
   "appId":"123456",
   "sign":"50b0c63834284359f2b231b4054d1e49",
   "pageIndex":1,
   "deviceId":"GTS0001" ,
   "pageSize":1
}
```
| 参数名称 | 数据类型|描述|
|--------|--------|------|---|
|  appId  |string| 0或无值表示正常，否则表示异常|
|  sign |string| 错误信息，用于客户端提示或用户处理|

### HTTP应答数据格式规范
```
{
  "errCode": 503,
  "errMsg": "非法请求，签名内容未通过验证"
}
```

### 服务端返回值定义
| 参数名称 | 数据类型|描述|
|--------|--------|------|---|
|  errCode  |number| 0或无值表示正常，否则表示异常|
|  errMsg |string| 错误信息，用于客户端提示或用户处理|

## HTTP连接签名算法

为了防止API调用过程中被黑客恶意篡改，调用任何一个API都需要携带签名，光速达智慧云服务端会根据请求参数，对签名进行验证，签名不合法的请求将会被拒绝。光速达智慧云目前支持的签名算法只支持MD5(sign_method=md5) ，签名大体过程如下：

将待签名参数（包括API的公共参数和业务参数，除去sign参数和byte[]类型的参数）使用英文冒号拼接参数的key和value，根据拼接后的字符串的ASCII码表的顺序排序。如：foo:1, bar:2, foo_bar:3, foobar:4排序后的顺序是bar:2, foo:1, foo_bar:3, foobar:4。
将排序好的字符串用英文逗号拼装在一起，在最后加上secret组成待签名字符串，根据上面的示例得到的结果为：bar:2,foo:1,foo_bar:3,foobar:4,secret:123456。
把待签名字符串使用MD5算法进行摘要，如：md5(bar:2,foo:1,foo_bar:3,foobar:4,secret=123456),将摘要得到的字节流结果输出为十六进制字符串。
说明：MD5是128位长度的摘要算法，用16进制表示，一个十六进制的字符能表示4个位，所以签名后的字符串长度固定为32个十六进制字符。

### 签名范例

以人闸接口调用为例，具体步骤如下：

1. 设置参数值

 公共参数：
```
appId=123456 //第三方用户唯一凭证
timestamp=1463535207898  //当前时间戳
nonstr=aaabbb  //随机字符串
```

 业务参数：
```
deviceId=GTS0001
pageSize=20
pageIndex=1
```

2. 用冒号拼接并按ASCII顺序排序
```
appId:123456
deviceId:GTS0001
nonstr:aaabbb
pageIndex:1
pageSize:20
timestamp:1463535207898
```
3. 拼接参数名与参数值
toSignStr=appId:123456,deviceId:GTS0001,nonstr:aaabbb,pageIndex:1,pageSize:20,timestamp:1463535207898

4. 生成签名
假设app的secret为123456，则签名结果为：hex(md5(toSignStr + ",secret:123456"))=bb4b98e26c9b916f74ada1137b7fc5aa

5. 组装HTTP请求
将所有参数名和参数值采用utf-8进行URL编码（参数顺序可随意，但必须要包括签名参数），然后通过GET或POST（含byte[]类型参数）发起请求，POST请求也可以使用application/json。

__URL示例：__
```
http://gtsc.leanapp.cn/gate/?appId=123456&deviceId=GTS0001&nonstr=aaabbb&pageIndex=1&pageSize=20&timestamp=1463535207898&sign=bb4b98e26c9b916f74ada1137b7fc5aa
```

- 注意事项

所有的请求和响应数据编码皆为utf-8格式，URL里的所有参数名和参数值请做URL编码。如果请求的Content-Type是application/x-www-form-urlencoded，则HTTP Body体里的所有参数值也做URL编码；如果是multipart/form-data格式，每个表单字段的参数值无需编码,但每个表单字段的charset部分需要指定为utf-8。
参数名与参数值拼装起来的URL长度小于1024个字符时，可以用GET发起请求；参数类型含byte[]类型或拼装好的请求URL过长时，必须用POST发起请求。所有API都可以用POST发起请求。
生成签名（sign）仅对未使用TOP官方SDK进行API调用时需要操作，如使用了TOP官方SDK，该步骤SDK会自动完成。

## 参考资料

## Group 光速号API

## Group 商城平台API

## Group 智慧社区API

## 购物车下单 [/1.1/function/createOrder]   

### 从购物车下单 [POST]

用户下单接口

+ Parameters
    + orderNo : `335566` (string) - 订单编号
    + seller : `5742a9da79bc44005cab2841` (string) - 商品提供者ObjectId
    + payType : `1` (string) - 支付方式 1、支付宝 2、微信 3、货到付款
    + reduceCost : `10` (number) - 优惠金额
    + orderAt : `2016-05-24 14:00:00` (string) - 下单时间
    + payAt : `2016-05-24 14:02:00` (string) - 支付时间
    + receiveAddress : `测试地址` (string) - 收获地址
    + userCouponId : `5743eb17a3413100625d7081` (string) - 订单编号
    + items : `[{}]` (array) - 订单商品项集合

+ Request (application/json)

   {
      orderNo:"335566",
      seller:"5742a9da79bc44005cab2841",
      payType:1,
      reduceCost:10,
      orderAt:"2016-05-24 14:00:00",
      payAt :"2016-05-24 14:02:00",
      receiveAddress:"测试地址",
      userCouponId:"5743eb17a3413100625d7081",
      items:[{
          trolleyId:"574565f22b51e900697ac1de",
          goodId:"573c1d0749830c00611a7a94",
          quantity:3,
          price:1,
          orderNo:"335566"
      },{
           trolleyId:"5742d05c1532bc0065a56e5e",
          goodId:"573c1a9adf0eea005e7a0ac5",
          quantity:8,
          price:356,
          orderNo:"335566"
      }]
   }

+ Response 200 (application/json)

    {
     "result": {
       "orderNo": "335566",
       "buyer": "5742a9da79bc44005cab2841",
       "seller": "5742a9da79bc44005cab2841",
       "payType": 1,
       "total": -9,
       "reduceCost": 10,
       "orderAt": "2016-05-24 14:00:00",
       "payAt": "2016-05-24 14:02:00",
       "transportCost": 0,
       "receiveAddress": "测试地址",
       "userCouponId": "5743eb17a3413100625d7081",
       "remark": "",
       "objectId": "57456c3171cfe4006bb8399f",
       "createdAt": "2016-05-25T09:11:13.925Z",
       "updatedAt": "2016-05-25T09:11:13.925Z"
     }
}

## 商品直接购买 [/1.1/function/buyNow]   

### 商品直接购买 [POST]

用户下单接口

+ Parameters
    + orderNo : `335566` (string) - 订单编号
    + seller : `5742a9da79bc44005cab2841` (string) - 商品提供者ObjectId
    + payType : `1` (string) - 支付方式 1、支付宝 2、微信 3、货到付款
    + reduceCost : `10` (number) - 优惠金额
    + orderAt : `2016-05-24 14:00:00` (string) - 下单时间
    + payAt : `2016-05-24 14:02:00` (string) - 支付时间
    + receiveAddress : `测试地址` (string) - 收获地址
    + userCouponId : `5743eb17a3413100625d7081` (string) - 订单编号
    + item : `[{}]` (array) - 订单商品项

+ Request (application/json)

  {
      orderNo:"335566",
      seller:"5742a9da79bc44005cab2841",
      payType:1,
      reduceCost:10,
      orderAt:"2016-05-24 14:00:00",
      payAt :"2016-05-24 14:02:00",
      receiveAddress:"测试地址",
      userCouponId:"5743eb17a3413100625d7081",
      item:{
          goodId:"573c1d0749830c00611a7a94",
          quantity:3,
          price:1,
          orderNo:"335566"
      }
  }
+ Response 200 (application/json)

    {
     "result": {
       "orderNo": "335566",
       "buyer": "5742a9da79bc44005cab2841",
       "seller": "5742a9da79bc44005cab2841",
       "payType": 1,
       "total": -9,
       "reduceCost": 10,
       "orderAt": "2016-05-24 14:00:00",
       "payAt": "2016-05-24 14:02:00",
       "transportCost": 0,
       "receiveAddress": "测试地址",
       "userCouponId": "5743eb17a3413100625d7081",
       "remark": "",
       "objectId": "57456c3171cfe4006bb8399f",
       "createdAt": "2016-05-25T09:11:13.925Z",
       "updatedAt": "2016-05-25T09:11:13.925Z"
     }
}
    
    
## 用户发布投诉表扬 [/1.1/function/addFeedBack]

### 用户发布投诉表扬 [POST]

方法名:addFeedBack

+ Request (application/json)

    {
        content:"楼下装修声音太大，很吵！",
      	nhNo:"572994182627f3053620b356",
      	picture : "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
      	propertyId:"5742a9da79bc44005cab2841",
      	type:1
   }

+ Response 200 (application/json)

    {
      "result": {
          "objectId": "57465c7b2e958a002daba825",
          "userId": "56ecbc32da2f60004c887c88",
          "type": 1,
          "content": "楼下装修声音太大，很吵！",
          "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
          "updateAt": "2016-05-26T02:16:27.693Z"
      }
   }


## 确认反馈记录 [/property/confirmFeedBack]

### 反馈记录确认 [POST]

物业确认用户提交的反馈记录。

方法名:confirmFeedBack

+ Request (application/json)

    {
        id:"5729ba9d2627f3053620c31b",
        lastSyncDate:"2016-05-24T10:03:13.514Z",
        sign:"",
        appId:""
    }

+ Response 200 (application/json)

    {
        "result": {
           "objectId": "574519e1c4c971002345eb25",
           "userId": "5742762979bc44005ca9bb3e",
           "userName": "李大塆",
           "type": 1,
           "content": "发现自行车丢了找物业，发现原来是忘记锁了物业把它放到安全的地方去了，这点做的很好",
           "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
           "confirmed": 1,
           "reply": ""
      }
    }

+ Response 500 (application/json)

 {
    "code": 305,
    "msg": "时间戳标签不一致！",
    "result": {
        "objectId": "574519e1c4c971002345eb25",
        "userId": "5742762979bc44005ca9bb3e",
        "userName": "李大塆",
        "type": 1,
        "content": "发现自行车丢了找物业，发现原来是忘记锁了物业把它放到安全的地方去了，这点做的很好",
        "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
        "confirmed": 1,
        "reply": ""
    }
}

## 回复反馈记录 [/property/reply]

### 回复用户反馈 [POST]

方法名：reply

对用户的反馈进行回复

+ Request (application/json)

    {
       id:"5729ba9d2627f3053620c31b",
       reply:"这是测试回复！",
       lastSyncDate:"2016-05-24T10:03:13.514Z",
       sign:"",
       appId:""
    }

+ Response 200 (application/json)

    {
        "result": {
             "objectId": "574519e1c4c971002345eb25",
             "userId": "5742762979bc44005ca9bb3e",
             "userName": "李大塆",
             "type": 1,
             "content": "发现自行车丢了找物业，发现原来是忘记锁了物业把它放到安全的地方去了，这点做的很好",
             "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
             "confirmed": 1,
             "reply": "这是测试回复！"
         }
    }

+ Response 500 (application/json)

{
    "code": 305,
    "msg": "回复失败，时间戳标签不一致!!",
    "result": {
        "objectId": "574519e1c4c971002345eb25",
        "userId": "5742762979bc44005ca9bb3e",
        "userName": "李大塆",
        "type": 1,
        "content": "发现自行车丢了找物业，发现原来是忘记锁了物业把它放到安全的地方去了，这点做的很好",
        "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
        "confirmed": 1,
        "reply": "这是测试回复！"
    }
}

## 查询反馈记录 [/property/feedList]

### 查询用户用户反馈记录 [GET]

方法名：feedList

查询用户反馈记录

+ Request (application/json)

    {
       lastSyncDate:"2016-05-24T10:03:13.514Z",
       sign:"",
       appId:""
    }

+ Response 200 (application/json)

   {
    "serverTime": "2016-5-25 14:54:52",
    "lists": [
        {
            "objectId": "574519e1c4c971002345eb26",
            "userId": "574250c52b51e90057b1dd10",
            "userName": "光速达测试号",
            "type": 1,
            "content": "水管漏水，联系物业，下午就来修了",
            "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
            "confirmed": 2,
            "reply": "这是我们应该做的"
        },
        {
            "objectId": "574519e1c4c971002345eb27",
            "userId": "574250c52b51e90057b1dd10",
            "userName": "光速达测试号",
            "type": 1,
            "content": "电梯坏了反馈给物业，一小时后就有人来修了",
            "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
            "confirmed": 2,
            "reply": "这是我们应该做的"
        },
        {
            "objectId": "574519e1c4c971002345eb25",
            "userId": "5742762979bc44005ca9bb3e",
            "userName": "李大塆",
            "type": 1,
            "content": "发现自行车丢了找物业，发现原来是忘记锁了物业把它放到安全的地方去了，这点做的很好",
            "picture": "http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//NjI0M2QxYjctZmRiMC00NWRmLTg5NTktMTY3MDRhZDE4M2UzcB1ICw.jpg,http://image-tdrz.oss-cn-shenzhen.aliyuncs.com/rt//Y2Q4MDIwNzgtZjQ0Yy00MTgxLWEyMTQtOTdiMzBiOWY2MDk3Elbjfw.jpg",
            "confirmed": 1,
            "reply": "这是测试回复！"
        }
    ]
   }

## Group 智慧酒店API

## Group 交易中心API

## Group 示例
## 人闸记录（测试） [/gate/?appId={appId}&deviceId={deviceId}&timestamp={timestamp}&nonstr={nonstr}&pageSize={pageSize}&pageIndex={pageIndex}&sign={sign}&lastSyncDate={lastSyncDate}]

### 获取人闸记录 [GET]

使用GET请求获取人闸记录。

+ Parameters
    + timestamp : `1463535207898` (number) - 请求提交的当前时间时间戳
    + lastSyncDate : `2016-04-19T02:06:57.931Z` (string) - 最后同步更新时间，如果不传获取所有的内容，日期格式必须是 `2016-04-19T02:06:57.931Z` 的 UTC 时间
    + nonstr : `aaabbb` (string) - 当前加密签名使用的随机字符串
    + deviceId : `GTS0001` (string) - 设备对应的ID号
    + sign : `0a20d32eda37038e2287ccf74b49e0f4` (string) - 签名算法为MD5（signStr + secret）
    + appId : `123456` (string) - 第三方用户唯一凭证
    + pageIndex : `0` (number) - 分页页数,从0开始
    + pageSize : `20` (number) - 每页条数

+ Response 200 (application/json)

        {
            "total": 1502,
            "count": 2,
            "data": [{
                "startTime": {
                    "__type": "Date",
                    "iso": "2016-04-30T16:00:00.000Z"
                },
                "deviceInfo": {
                    "__type": "Pointer",
                    "className": "GateInfo",
                    "objectId": "5731cef41ea4930064fb8121"
                },
                "deviceId": "GTS0001",
                "endTime": {
                    "__type": "Date",
                    "iso": "2017-01-31T16:00:00.000Z"
                },
                "mobileIdentification": "EO9EBF0MSHC1NJJDQFLFP9ANIX9HGAUB",
                "mobile": "08081009592",
                "objectId": "573acce90a1aa41f53bf1944",
                "createdAt": "2016-05-17T07:48:57.375Z",
                "updatedAt": "2016-05-17T07:48:57.375Z"
            }]
        }

+ Response 503 (application/json)

        {
            "errCode": 503,
            "errMsg": "非法请求，签名内容未通过验证"
        }

### 获取人闸记录2 [POST]

使用POST请求获取人闸记录。

+ Request (application/json)

        {
            "sign": "0a20d32eda37038e2287ccf74b49e0f4",
            "timestamp": 1463535207898,
            "lastSyncDate": "2016-04-19T02:06:57.931Z",
            "appId": "123456",
            "nonstr": "aaabbb",
            "pageSize": 20,
            "deviceId": "GTS0001",
            "pageIndex": 0
        }

+ Response 200 (application/json)

        {
            "total": 1502,
            "count": 2,
            "data": [{
                "startTime": {
                    "__type": "Date",
                    "iso": "2016-04-30T16:00:00.000Z"
                },
                "deviceInfo": {
                    "__type": "Pointer",
                    "className": "GateInfo",
                    "objectId": "5731cef41ea4930064fb8121"
                },
                "deviceId": "GTS0001",
                "endTime": {
                    "__type": "Date",
                    "iso": "2017-01-31T16:00:00.000Z"
                },
                "mobileIdentification": "EO9EBF0MSHC1NJJDQFLFP9ANIX9HGAUB",
                "mobile": "08081009592",
                "objectId": "573acce90a1aa41f53bf1944",
                "createdAt": "2016-05-17T07:48:57.375Z",
                "updatedAt": "2016-05-17T07:48:57.375Z"
            }]
        }

+ Response 503 (application/json)

        {
            "errCode": 503,
            "errMsg": "非法请求，签名内容未通过验证"
        }
